module TexMindbody
    module Api
        module Model
            class Client < ModelBase
                attr_accessor :appointment_gender_preference, :birth_date, :country, :creation_date, :custom_client_fields, :client_credit_card, :client_indexes, :client_relationships, :first_appointment_date, :first_name, :id, :is_company, :is_prospect, :last_name, :liability, :liability_release, :membership_icon, :mobile_provider, :notes, :state, :unique_id, :last_modified_date_time, :red_alert, :yellow_alert, :middle_name, :prospect_stage, :email, :mobile_phone, :home_phone, :work_phone, :account_balance, :address_line1, :address_line2, :city, :postal_code, :work_extension, :referred_by, :photo_url, :emergency_contact_info_name, :emergency_contact_info_email, :emergency_contact_info_phone, :emergency_contact_info_relationship, :gender, :last_formula_notes, :active, :sales_reps, :status, :action, :send_account_emails, :send_account_texts, :send_promotional_emails, :send_promotional_texts, :send_schedule_emails, :send_schedule_texts
                def initialize k = {}
                    @appointment_gender_preference = k['AppointmentGenderPreference']
                    @birth_date = k['BirthDate']
                    @country = k['Country']
                    @creation_date = k['CreationDate']
                    @custom_client_fields = k['CustomClientFields']
                    @client_credit_card = k['ClientCreditCard']
                    @client_indexes = k['ClientIndexes']
                    @client_relationships = k['ClientRelationships']
                    @first_appointment_date = k['FirstAppointmentDate']
                    @first_name = k['FirstName']
                    @id = k['Id']
                    @is_company = k['IsCompany']
                    @is_prospect = k['IsProspect']
                    @last_name = k['LastName']
                    @liability = k['Liability']
                    @liability_release = k['LiabilityRelease']
                    @membership_icon = k['MembershipIcon']
                    @mobile_provider = k['MobileProvider']
                    @notes = k['Notes']
                    @state = k['State']
                    @unique_id = k['UniqueId']
                    @last_modified_date_time = k['LastModifiedDateTime']
                    @red_alert = k['RedAlert']
                    @yellow_alert = k['YellowAlert']
                    @middle_name = k['MiddleName']
                    @prospect_stage = k['ProspectStage']
                    @email = k['Email']
                    @mobile_phone = k['MobilePhone']
                    @home_phone = k['HomePhone']
                    @work_phone = k['WorkPhone']
                    @account_balance = k['AccountBalance']
                    @address_line1 = k['AddressLine1']
                    @address_line2 = k['AddressLine2']
                    @city = k['City']
                    @postal_code = k['PostalCode']
                    @work_extension = k['WorkExtension']
                    @referred_by = k['ReferredBy']
                    @photo_url = k['PhotoUrl']
                    @emergency_contact_info_name = k['EmergencyContactInfoName']
                    @emergency_contact_info_email = k['EmergencyContactInfoEmail']
                    @emergency_contact_info_phone = k['EmergencyContactInfoPhone']
                    @emergency_contact_info_relationship = k['EmergencyContactInfoRelationship']
                    @gender = k['Gender']
                    @last_formula_notes = k['LastFormulaNotes']
                    @active = k['Active']
                    @sales_reps = k['SalesReps']
                    @status = k['Status']
                    @action = k['Action']
                    @send_account_emails = k['SendAccountEmails']
                    @send_account_texts = k['SendAccountTexts']
                    @send_promotional_emails = k['SendPromotionalEmails']
                    @send_promotional_texts = k['SendPromotionalTexts']
                    @send_schedule_emails = k['SendScheduleEmails']
                    @send_schedule_texts = k['SendScheduleTexts']
                end
            end
        end
    end
end